# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ice_cream_pb2 as ice__cream__pb2


class IceCreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OrderIceCream = channel.unary_unary(
                '/IceCream/OrderIceCream',
                request_serializer=ice__cream__pb2.IceCreamRequest.SerializeToString,
                response_deserializer=ice__cream__pb2.IceCreamResponse.FromString,
                )


class IceCreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OrderIceCream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IceCreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OrderIceCream': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderIceCream,
                    request_deserializer=ice__cream__pb2.IceCreamRequest.FromString,
                    response_serializer=ice__cream__pb2.IceCreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IceCream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IceCream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OrderIceCream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IceCream/OrderIceCream',
            ice__cream__pb2.IceCreamRequest.SerializeToString,
            ice__cream__pb2.IceCreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
